# Generated by Django 4.2.4 on 2023-10-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='location',
            field=models.CharField(default='Karachi', max_length=100),
        ),
    ]
